# nfpm configuration file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "ziti-cli"
arch: "${GOARCH}"
platform: "linux"
version: "${ZITI_VERSION}"
# section: default
# priority: optional
# replaces:
# - foobar
# provides:
# - bar
# depends:
# - foo
# - bar
# recommends:
# - whatever
# suggests:
# - something-else
# conflicts:
# - not-foo
# - not-bar
maintainer: "${ZITI_MAINTAINER}"
description: |
  The ziti-cli package provides the ziti executable binary as a command line interface for Ziti.
vendor: "${ZITI_VENDOR}"
homepage: "${ZITI_HOMEPAGE}"
license: Apache-2.0
# changelog: "changelog.yaml"
contents:
- src: ./release/ziti
  dst: /usr/bin/ziti
# - src: ./foobar.conf
#   dst: /etc/foobar.conf
#   type: config
# - src: /usr/bin/foo
#   dst: /sbin/foo
#   type: symlink
# overrides:
  # rpm:
  #   scripts:
  #     preinstall: ./scripts/preinstall.sh
  #     postremove: ./scripts/postremove.sh
  # deb:
  #   scripts:
  #     postinstall: ./scripts/postinstall.sh
  #     preremove: ./scripts/preremove.sh
