# nfpm configuration file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: ziti-cli
arch: ${GOARCH}
platform: linux
version: ${ZITI_VERSION}
maintainer: ${ZITI_MAINTAINER}
description: >
  The ziti-cli package provides the ziti executable binary as a command line
  interface for Ziti.
vendor: ${ZITI_VENDOR}
homepage: ${ZITI_HOMEPAGE}
license: Apache-2.0
contents:
- src: ./release/ziti
  dst: /usr/bin/ziti
  file_info:
    mode: 0755
