name: Publish Linux Install Packages

on:
  workflow_call:
    inputs:
      ziti-version:
        description: 'Tag or Branch Ref to Publish'
        type: string
        required: true

jobs:
  publish-linux-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - goreleaser: amd64
            gox: amd64
          - goreleaser: arm64
            gox: arm64
          - goreleaser: armv7
            gox: arm
        nfpm_packager:
          - rpm
          - deb
          # - archlinux
          # - apk
    env:
      ZITI_VERSION: ${{ inputs.ziti-version || github.event.inputs.ziti-version }}
      ZITI_MAINTAINER: "OpenZiti Maintainers <ziggy@openziti.io>"
      ZITI_HOMEPAGE: "https://openziti.io"
      ZITI_VENDOR: "NetFoundry"
      GOARCH: ${{ matrix.arch.goreleaser }}
    steps:
      - name: Checkout Workspace
        uses: actions/checkout@v3

      - name: Download Linux Release Artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-release-${{ github.run_id }}
          path: release/

      - run: ls -lhR release/

      - run: mv -v ./release/${{ matrix.arch.gox }}/linux/ziti ./release/ziti

      - name: Build Package
        id: nfpm
        uses: burningalchemist/action-gh-nfpm@v1
        with:
          nfpm_version: "2.32.0"
          packager: ${{ matrix.nfpm_packager }}
          config: .github/nfpm-configs/nfpm-linux-ziti-cli.yaml
          # target: package.rpm

      - name: get the package name from the output
        run: echo ${{ steps.nfpm.outputs.package }}
        shell: bash
